# -*- coding: utf-8 -*-
"""SKN16-1st-5Team.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wV-nS3uyiD_IIULaWGinOVYJNwof2RQA
"""

# !pip -q install folium pandas streamlit streamlit-folium streamlit-antd-components
# !npm install -g localtunnel

# 나눔고딕 폰트 설치 및 설정
# !apt-get update -qq
# !apt-get install fonts-nanum -qq
# !fc-cache -fv
# !rm ~/.cache/matplotlib -rf

import matplotlib.pyplot as plt
import streamlit as st
import streamlit_antd_components as sac

# 모듈에서 함수 import
from contents.dashboard import show_dashboard
from contents.faq import show_faq

# 폰트 설정
# font_path = '/usr/share/fonts/truetype/nanum/NanumGothic.ttf'
# fontprop = fm.FontProperties(fname=font_path, size=10)
plt.rcParams["font.family"] = "NanumGothic"
plt.rcParams["axes.unicode_minus"] = False

# !wget -q -O - ipv4.icanhazip.com

# -------------------- 페이지 설정 --------------------
st.set_page_config(page_title="Team 5 App", layout="wide")

# -------------------- 사이드바 메뉴 --------------------
st.sidebar.title("Team 5")
with st.sidebar:
    selected_menu = sac.menu(
        [
            sac.MenuItem("Dashboard", icon=sac.AntIcon(name="DashboardOutlined")),
            sac.MenuItem(
                "FAQ",
                icon=sac.AntIcon(name="MessageOutlined"),
                children=[
                    sac.MenuItem(
                        "기아", icon=sac.AntIcon(name="UnorderedListOutlined")
                    ),
                    sac.MenuItem(
                        "제네시스", icon=sac.AntIcon(name="UnorderedListOutlined")
                    ),
                    sac.MenuItem(
                        "벤츠", icon=sac.AntIcon(name="UnorderedListOutlined")
                    ),
                ],
            ),
        ],
        color="blue",
    )

# -------------------- 메뉴에 따라 페이지 라우팅 --------------------
if selected_menu == "Dashboard":
    # dashboard 함수 실행
    show_dashboard()
elif selected_menu == "기아":
    show_faq("KIA")
elif selected_menu == "제네시스":
    show_faq("Genesis")
elif selected_menu == "벤츠":
    show_faq("Benz")
else:
    sac.result(label="404", description="404 에러입니다.", status=404)


# Commented out IPython magic to ensure Python compatibility.
# # python 파일 생성
# %%writefile app.py

# !streamlit run app.py & npx localtunnel --port 8501
